insert into public.words (
    id,
    word,
    pronunciation,
    part_of_speech,
    definition,
    example,
    difficulty,
    sort_order,
    is_active,
    published_at,
    source_name,
    license_name
)
values
    ('beginner-brisk', 'brisk', 'brisk', 'adjective', 'Quick, lively, and full of energy.', 'We took a brisk walk before breakfast.', 'beginner', 0, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-cozy', 'cozy', 'KOH-zee', 'adjective', 'Warm, comfortable, and relaxing.', 'The reading corner felt cozy on the rainy day.', 'beginner', 1, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-dazzle', 'dazzle', 'DAZ-uhl', 'verb', 'To impress someone with brightness or skill.', 'The dancer''s quick steps dazzled the crowd.', 'beginner', 2, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-eager', 'eager', 'EE-ger', 'adjective', 'Excited and ready to do something.', 'Maya was eager to open her new book.', 'beginner', 3, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-flutter', 'flutter', 'FLUT-er', 'verb', 'To move with quick, light motions.', 'The little flag began to flutter in the breeze.', 'beginner', 4, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-glimpse', 'glimpse', 'glimps', 'noun', 'A quick or partial look.', 'We caught a glimpse of the deer in the woods.', 'beginner', 5, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-harmony', 'harmony', 'HAR-muh-nee', 'noun', 'A pleasing way that sounds or people work together.', 'Their voices blended in harmony.', 'beginner', 6, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-invent', 'invent', 'in-VENT', 'verb', 'To create something that did not exist before.', 'They worked together to invent a new game.', 'beginner', 7, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-jolly', 'jolly', 'JOL-ee', 'adjective', 'Happy, cheerful, and friendly.', 'Our jolly neighbor waved from across the street.', 'beginner', 8, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-keen', 'keen', 'keen', 'adjective', 'Very interested, eager, or sharp.', 'Noah has a keen eye for small details.', 'beginner', 9, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-linger', 'linger', 'LING-ger', 'verb', 'To stay somewhere a little longer.', 'The smell of cinnamon seemed to linger.', 'beginner', 10, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-mend', 'mend', 'mend', 'verb', 'To repair something that is damaged.', 'I used a patch to mend the tiny tear.', 'beginner', 11, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-nifty', 'nifty', 'NIF-tee', 'adjective', 'Especially good, clever, or useful.', 'That folding stool is a nifty idea.', 'beginner', 12, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-observe', 'observe', 'ub-ZURV', 'verb', 'To watch or notice something carefully.', 'We sat quietly to observe the birds.', 'beginner', 13, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-peculiar', 'peculiar', 'pih-KYOOL-yur', 'adjective', 'Unusual or a little strange.', 'A peculiar sound came from the old clock.', 'beginner', 14, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-radiant', 'radiant', 'RAY-dee-unt', 'adjective', 'Shining brightly or showing great happiness.', 'Her radiant smile welcomed everyone.', 'beginner', 15, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-sturdy', 'sturdy', 'STUR-dee', 'adjective', 'Strong and not easily damaged.', 'The sturdy bridge held up through the storm.', 'beginner', 16, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-tranquil', 'tranquil', 'TRANG-kwil', 'adjective', 'Quiet, calm, and peaceful.', 'The garden was tranquil just after sunrise.', 'beginner', 17, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-venture', 'venture', 'VEN-chur', 'noun', 'A new activity that may be exciting or risky.', 'The bake sale was their first business venture.', 'beginner', 18, true, now(), 'Eight Words original', 'Proprietary'),
    ('beginner-whimsical', 'whimsical', 'WIM-zih-kul', 'adjective', 'Playfully unusual or imaginative.', 'The artist filled the wall with whimsical animals.', 'beginner', 19, true, now(), 'Eight Words original', 'Proprietary'),

    ('intermediate-adapt', 'adapt', 'uh-DAPT', 'verb', 'To change in order to fit a new situation.', 'Plants adapt to the amount of light they receive.', 'intermediate', 0, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-benevolent', 'benevolent', 'buh-NEV-uh-lunt', 'adjective', 'Kind and generous toward others.', 'A benevolent donor supplied books for the library.', 'intermediate', 1, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-candid', 'candid', 'KAN-did', 'adjective', 'Honest and direct, even when the truth is difficult.', 'She gave a candid answer about the project.', 'intermediate', 2, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-diligent', 'diligent', 'DIL-ih-junt', 'adjective', 'Careful and persistent in your work.', 'His diligent practice made the song sound effortless.', 'intermediate', 3, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-eloquent', 'eloquent', 'EL-uh-kwunt', 'adjective', 'Fluent, clear, and persuasive in expression.', 'Her eloquent speech moved the audience.', 'intermediate', 4, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-frugal', 'frugal', 'FROO-gul', 'adjective', 'Careful about spending money or using resources.', 'Packing lunch is a frugal habit.', 'intermediate', 5, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-gratify', 'gratify', 'GRAT-uh-fy', 'verb', 'To give pleasure or satisfaction.', 'It gratified him to see the garden thrive.', 'intermediate', 6, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-hypothesis', 'hypothesis', 'hy-POTH-uh-sis', 'noun', 'An idea that can be tested to see if it is true.', 'Our hypothesis predicted which seed would sprout first.', 'intermediate', 7, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-impartial', 'impartial', 'im-PAR-shul', 'adjective', 'Fair and not favoring one side.', 'The judge remained impartial during the debate.', 'intermediate', 8, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-jovial', 'jovial', 'JOH-vee-ul', 'adjective', 'Friendly, cheerful, and good-humored.', 'His jovial greeting put everyone at ease.', 'intermediate', 9, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-kinetic', 'kinetic', 'kih-NET-ik', 'adjective', 'Related to motion or produced by movement.', 'The sculpture turns wind into kinetic energy.', 'intermediate', 10, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-lucid', 'lucid', 'LOO-sid', 'adjective', 'Expressed clearly and easy to understand.', 'The guide gave a lucid explanation of the rules.', 'intermediate', 11, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-meticulous', 'meticulous', 'muh-TIK-yuh-lus', 'adjective', 'Very careful about small details.', 'She kept meticulous notes during the experiment.', 'intermediate', 12, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-novel', 'novel', 'NOV-uhl', 'adjective', 'New, original, or unusual.', 'The team found a novel solution to the problem.', 'intermediate', 13, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-optimistic', 'optimistic', 'op-tuh-MIS-tik', 'adjective', 'Expecting good things to happen.', 'Despite the delay, the hikers stayed optimistic.', 'intermediate', 14, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-pragmatic', 'pragmatic', 'prag-MAT-ik', 'adjective', 'Focused on practical results.', 'We chose the most pragmatic plan for the time available.', 'intermediate', 15, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-resilient', 'resilient', 'rih-ZIL-yunt', 'adjective', 'Able to recover quickly after difficulty.', 'The resilient little tree grew after the fire.', 'intermediate', 16, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-scrutinize', 'scrutinize', 'SKROOT-n-eyes', 'verb', 'To examine something very carefully.', 'The editor will scrutinize every sentence.', 'intermediate', 17, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-tangible', 'tangible', 'TAN-juh-bul', 'adjective', 'Real, clear, or able to be touched.', 'Finishing the first chapter was tangible progress.', 'intermediate', 18, true, now(), 'Eight Words original', 'Proprietary'),
    ('intermediate-versatile', 'versatile', 'VUR-suh-tyl', 'adjective', 'Able to do many different things well.', 'A plain notebook is a versatile tool.', 'intermediate', 19, true, now(), 'Eight Words original', 'Proprietary'),

    ('advanced-ameliorate', 'ameliorate', 'uh-MEEL-yuh-rayt', 'verb', 'To make an unpleasant situation better.', 'New shade trees may ameliorate the summer heat.', 'advanced', 0, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-bucolic', 'bucolic', 'byoo-KOL-ik', 'adjective', 'Relating to the pleasant aspects of the countryside.', 'The painting shows a bucolic scene of fields and sheep.', 'advanced', 1, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-circumspect', 'circumspect', 'SUR-kum-spekt', 'adjective', 'Careful to consider possible risks before acting.', 'The board was circumspect about making a quick decision.', 'advanced', 2, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-deleterious', 'deleterious', 'del-uh-TEER-ee-us', 'adjective', 'Causing harm or damage.', 'Too little sleep can have a deleterious effect on focus.', 'advanced', 3, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-ephemeral', 'ephemeral', 'ih-FEM-er-ul', 'adjective', 'Lasting for only a short time.', 'The artist created an ephemeral pattern in the sand.', 'advanced', 4, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-fastidious', 'fastidious', 'fa-STID-ee-us', 'adjective', 'Very attentive to accuracy and detail.', 'The fastidious baker measured every ingredient twice.', 'advanced', 5, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-gregarious', 'gregarious', 'grih-GAIR-ee-us', 'adjective', 'Sociable and fond of company.', 'Her gregarious nature made newcomers feel welcome.', 'advanced', 6, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-heuristic', 'heuristic', 'hyoo-RIS-tik', 'noun', 'A practical shortcut used to solve a problem or learn something.', 'The rule of thumb was a useful heuristic.', 'advanced', 7, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-ineffable', 'ineffable', 'in-EF-uh-bul', 'adjective', 'Too great or unusual to be expressed in words.', 'They watched the eclipse with ineffable wonder.', 'advanced', 8, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-juxtapose', 'juxtapose', 'JUK-stuh-pohz', 'verb', 'To place things together to highlight their differences.', 'The exhibit will juxtapose ancient tools with modern ones.', 'advanced', 9, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-laconic', 'laconic', 'luh-KON-ik', 'adjective', 'Using very few words.', 'His laconic reply left no room for debate.', 'advanced', 10, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-mellifluous', 'mellifluous', 'muh-LIF-loo-us', 'adjective', 'Pleasantly smooth and musical to hear.', 'The narrator''s mellifluous voice suited the bedtime story.', 'advanced', 11, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-nuance', 'nuance', 'NOO-ahns', 'noun', 'A subtle difference in meaning, feeling, or appearance.', 'The actor captured every nuance of the character.', 'advanced', 12, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-obfuscate', 'obfuscate', 'OB-fuh-skayt', 'verb', 'To make something unclear or difficult to understand.', 'Extra jargon can obfuscate a simple idea.', 'advanced', 13, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-perspicacious', 'perspicacious', 'pur-spih-KAY-shus', 'adjective', 'Quick to notice and understand difficult things.', 'Her perspicacious questions revealed the plan''s weakness.', 'advanced', 14, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-quixotic', 'quixotic', 'kwik-SOT-ik', 'adjective', 'Extremely idealistic but not very practical.', 'His quixotic plan involved sailing around the world in a month.', 'advanced', 15, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-reticent', 'reticent', 'RET-ih-sunt', 'adjective', 'Not revealing thoughts or feelings readily.', 'She was reticent at first, then shared her idea.', 'advanced', 16, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-sagacious', 'sagacious', 'suh-GAY-shus', 'adjective', 'Showing wise judgment and good sense.', 'The sagacious mentor encouraged patience.', 'advanced', 17, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-ubiquitous', 'ubiquitous', 'yoo-BIK-wih-tus', 'adjective', 'Present or found nearly everywhere.', 'Smartphones have become ubiquitous in many cities.', 'advanced', 18, true, now(), 'Eight Words original', 'Proprietary'),
    ('advanced-verisimilitude', 'verisimilitude', 'ver-uh-sih-MIL-ih-tood', 'noun', 'The appearance of being true or real.', 'Small historical details gave the story verisimilitude.', 'advanced', 19, true, now(), 'Eight Words original', 'Proprietary')
on conflict (id) do update set
    word = excluded.word,
    pronunciation = excluded.pronunciation,
    part_of_speech = excluded.part_of_speech,
    definition = excluded.definition,
    example = excluded.example,
    difficulty = excluded.difficulty,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    published_at = excluded.published_at,
    source_name = excluded.source_name,
    license_name = excluded.license_name,
    updated_at = now();
